[[redirects]]
  from = "/api/chat"
  to = "https://script.google.com/macros/s/AKfycbzG1Q22LCOzqyXUwrTzxkqi5csH_yhQdQCAgZqsky0LB2YTiVHD7NttkGkDS6ilcyp7eg/exec"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
