[[redirects]]
  from = "/api/orders"
  to = "https://script.google.com/macros/s/AKfycbx6i6Yn7ezXqwJKgZF3Mbq_MbgNeb4mQ8weT0Qipu0c9ASFRVK6l-HIdH83xFbJOeI4/exec"
  status = 200
  force = true

[[redirects]]
  from = "/api/chat"
  to = "https://script.google.com/macros/s/AKfycbzG1Q22LCOzqyXUwrTzxkqi5csH_yhQdQCAgZqsky0LB2YTiVHD7NttkGkDS6ilcyp7eg/exec"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
